### ISSUE TITLE
how to keep action in file（.fbx）

### ISSUE THREAD

**Issue by Acnext** [owl-project/NVISII#98] opened 2021-04-01 07:39 UTC
l try to import a file .fbx but it seems only a object is kept and how to import corresponding transform?

**Comment by n8vm** [comment] 2021-04-02 14:42
hm, are you using the `mesh.create_from_file` function? Or the `nvisii.import_scene` function? The latter should respect FBX transforms, although I'm not sure I've tested that as thoroughly as I should.

**Comment by Acnext** [comment] 2021-04-05 02:50
emmm, I am a beginner and use the nvisii.import_scene function as,
```python
  sdb = nvisii.import_scene(
      file_path = 'resources/Golf.fbx',
      position = (1,0,0),
      scale = (1.0, 1.0, 1.0),
  )
  
  # # # # # # # # # # # # # # # # # # # # # # # # #
  for i in range(10):   
      nvisii.render_to_file(
          width=opt.width, 
          height=opt.height, 
          samples_per_pixel=opt.spp,
          file_path=str(i) + opt.out
      )
  # let's clean up the GPU
  nvisii.deinitialize()
```
the Golf.fbx is ，
![image](https://user-images.githubusercontent.com/38678632/113531774-35181500-95fc-11eb-9aae-b30e964e61ff.png)
and describe the action to play golf
but l get this by using above code，
![image](https://user-images.githubusercontent.com/38678632/113531844-6b559480-95fc-11eb-883d-5b142057a8c0.png)
What related code l need to add to keep the action and Material？

**Comment by n8vm** [comment] 2021-04-05 03:06
Ah, sorry, we do not currently support importing rigged and animated fbx files. For the moment, you will need to bake out the time steps of your animation to separate fbx files. That’s probably what’s the cause of the issue. For the moment, a workaround is to save each animation timestep as a different fbx file.

In the future I’d like to add support for animated fbx files, but that would require some additional API changes (maybe a nvisii.set_time function?).

As for the issue with materials, this should be fixed now on development, and will soon be merged into master and pushed to pip.

**Comment by Acnext** [comment] 2021-04-05 03:30
Thanks a lot

**Closed** 2021-04-14 23:59 UTC
